# settings.yaml
box_name: "bento/ubuntu-22.04"
vm:
- name: "controlplane"
  ip: "192.168.201.10"
  memory: "2048"
  cpus: "2"
- name: "production"
  ip: "192.168.201.11"
  memory: "2048"
  cpus: "1"
- name: "QA"
  ip: "192.168.201.12"
  memory: "2048"
  cpus: "1"
- name: "sonar"
  ip: "192.168.201.13"
  memory: "2048"
  cpus: "1"
- name: "jenkins"
  ip: "192.168.201.14"
  memory: "2048"
  cpus: "1"
- name: "artifactory"
  ip: "192.168.201.15"
  memory: "2048"
  cpus: "1"
